### ISSUE TITLE
Fun Slides: To-Do List

### ISSUE THREAD

**Issue by aapatre** [aapatre/fun-slides#1]
## To-Do List

Create a custom Gutenberg Slider block with the following requirements:

### Back-End :back: :end: 

- [x] Provide editor to upload either images or videos
- [x] Ratio for slider 500x300
- [x] Editor should be able to link individual image video to external links, provide an option to facilitate the same
- [x] Editor should be able to add a CTA button on the slide and add text + link it
- [x] Option to enable/disable: the dots below the slider
- [x] Option to enable/disable: the right and left arrows
- [x] Option to enable/disable auto transition (if enabled - enter the value with regards to milliseconds)
- [x] If a video is uploaded and it's playtime exceeds the value set in auto transition, the video should be able to play it's the entire length and transition to the next slide and go back to respecting the auto transition value set
- [x] As much as possible, the backend should resemble the front-end

### On Front-End :sparkles: 

- [x] It should be able to display images and videos
- [x] Have small dots below media to indicate the number of slides active
- [x] Interactive arrows on the right and left side to switch with between slides
- [x] Should be responsive
- [x] Have a CTA button for users to interact with
- [x] If the image and video is linked to any external link, upon clicking the link should open in a new tab
